"""Restore inert scrollback and shell history before starting a normal shell."""

from __future__ import annotations

import os
import pwd
import shlex
import shutil
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import NoReturn

from .context import (
    COMMAND_HISTORY_LIMIT,
    ContextInput,
    pane_auto_run_argv,
    pane_command_history,
    pane_terminal_history,
)
from .filesystem import atomic_write_text
from .store import StoredSession

ZSH_HISTORY_SIZE = COMMAND_HISTORY_LIMIT + 1
SGR_RESET = "\x1b[0m"


def _history_line(command: str) -> str:
    """Flatten one command into a safe, recallable shell-history record."""
    flattened = " ".join(command.replace("\r", "\n").splitlines())
    return "".join(
        character
        for character in flattened
        if character == "\t" or (ord(character) >= 0x20 and character != "\x7f")
    ).strip()


def _original_zdotdir(environment: Mapping[str, str], state_directory: Path) -> str:
    """Recover the user's ZDOTDIR without recursively sourcing generated files."""
    configured = environment.get("ZDOTDIR", "")
    marker = state_directory / "original-zdotdir"
    if configured:
        try:
            points_to_state = Path(configured).expanduser().resolve() == state_directory.resolve()
        except OSError:
            points_to_state = False
        if not points_to_state:
            return configured
    if marker.is_file():
        return marker.read_text(encoding="utf-8").rstrip("\n")
    return ""


def prepare_zsh_startup(
    stored: StoredSession,
    context: ContextInput,
    tab_index: int,
    pane_index: int,
    environment: Mapping[str, str],
) -> Path | None:
    """Create private zsh startup files that source user config and import history."""
    commands = [
        line
        for item in pane_command_history(context, tab_index, pane_index)
        if (line := _history_line(item))
    ]
    if not commands:
        return None

    state_directory = (
        stored.directory / "shell-state" / f"tab-{tab_index:04d}-pane-{pane_index:04d}"
    )
    state_directory.mkdir(parents=True, exist_ok=True)
    original_zdotdir = _original_zdotdir(environment, state_directory)
    home = environment.get("HOME") or str(Path.home())
    user_rc_directory = Path(original_zdotdir or home).expanduser()
    user_zshenv = user_rc_directory / ".zshenv"
    history_path = state_directory / "history"
    marker_path = state_directory / "original-zdotdir"

    atomic_write_text(
        history_path,
        "\n".join(commands[-COMMAND_HISTORY_LIMIT:]) + "\n",
        mode=0o600,
    )
    atomic_write_text(marker_path, original_zdotdir + "\n", mode=0o600)

    original_zdotdir_setup = (
        f"export ZDOTDIR={shlex.quote(original_zdotdir)}" if original_zdotdir else "unset ZDOTDIR"
    )
    zshenv = (
        "\n".join(
            (
                "# Generated by kitty-workbench; preserve normal zsh startup semantics.",
                original_zdotdir_setup,
                f"if [[ -r {shlex.quote(str(user_zshenv))} ]]; then",
                f"  builtin source -- {shlex.quote(str(user_zshenv))}",
                "fi",
                "if (( ${+ZDOTDIR} )); then",
                "  export KITTY_WORKBENCH_USER_ZDOTDIR_SET=1",
                '  export KITTY_WORKBENCH_USER_ZDOTDIR_VALUE="$ZDOTDIR"',
                "else",
                "  export KITTY_WORKBENCH_USER_ZDOTDIR_SET=0",
                "  export KITTY_WORKBENCH_USER_ZDOTDIR_VALUE=",
                "fi",
                f"export ZDOTDIR={shlex.quote(str(state_directory))}",
            )
        )
        + "\n"
    )
    rc = (
        "\n".join(
            (
                "# Generated by kitty-workbench. Session data is inert until recalled.",
                "if [[ $KITTY_WORKBENCH_USER_ZDOTDIR_SET == 1 ]]; then",
                '  export ZDOTDIR="$KITTY_WORKBENCH_USER_ZDOTDIR_VALUE"',
                "  [[ -n $ZDOTDIR ]] && "
                'typeset _kitty_workbench_user_zshrc="$ZDOTDIR/.zshrc" || '
                "typeset _kitty_workbench_user_zshrc=/.zshrc",
                "else",
                "  unset ZDOTDIR",
                '  typeset _kitty_workbench_user_zshrc="$HOME/.zshrc"',
                "fi",
                "if [[ -r $_kitty_workbench_user_zshrc ]]; then",
                '  builtin source -- "$_kitty_workbench_user_zshrc"',
                "fi",
                f"(( HISTSIZE < {ZSH_HISTORY_SIZE} )) && typeset -g HISTSIZE={ZSH_HISTORY_SIZE}",
                f"builtin fc -R -- {shlex.quote(str(history_path))}",
                "unset _kitty_workbench_user_zshrc KITTY_WORKBENCH_RESTORING_SHELL",
                "unset KITTY_WORKBENCH_USER_ZDOTDIR_SET KITTY_WORKBENCH_USER_ZDOTDIR_VALUE",
            )
        )
        + "\n"
    )
    atomic_write_text(state_directory / ".zshenv", zshenv, mode=0o600)
    atomic_write_text(state_directory / ".zshrc", rc, mode=0o600)
    return state_directory


def _configured_shell(environment: Mapping[str, str]) -> str:
    """Resolve the user's configured shell with a passwd database fallback."""
    configured = environment.get("SHELL", "").strip()
    if configured:
        return configured
    try:
        return pwd.getpwuid(os.getuid()).pw_shell or "/bin/sh"
    except (KeyError, OSError):
        return "/bin/sh"


def _kitten_executable(environment: Mapping[str, str]) -> str:
    """Resolve kitten from explicit configuration, PATH, or the macOS app."""
    configured = environment.get("KITTY_WORKBENCH_KITTEN")
    if configured and Path(configured).is_file():
        return configured
    if found := shutil.which("kitten", path=environment.get("PATH")):
        return found
    app_binary = Path("/Applications/kitty.app/Contents/MacOS/kitten")
    if app_binary.is_file():
        return str(app_binary)
    raise OSError("cannot find the kitten executable needed to restore a shell")


def shell_launch_command(
    stored: StoredSession,
    context: ContextInput,
    tab_index: int,
    pane_index: int,
    environment: Mapping[str, str],
    startup_argv: Sequence[str] = (),
) -> list[str]:
    """Build a kitten run-shell command with optional private zsh startup."""
    shell = _configured_shell(environment)
    try:
        shell_name = Path(shlex.split(shell)[0]).name.lstrip("-").casefold()
    except (IndexError, ValueError):
        shell_name = ""
    command = [_kitten_executable(environment), "run-shell", f"--shell={shell}"]
    if shell_name == "zsh" and (
        zdotdir := prepare_zsh_startup(stored, context, tab_index, pane_index, environment)
    ):
        command.extend(
            (
                f"--env=ZDOTDIR={zdotdir}",
                "--env=KITTY_WORKBENCH_RESTORING_SHELL=1",
            )
        )
    if startup_argv:
        command.extend(("--", *startup_argv))
    return command


def run_restored_shell(
    stored: StoredSession,
    context: ContextInput,
    tab_index: int,
    pane_index: int,
) -> NoReturn:
    """Render saved scrollback, then replace this helper with the user's shell."""
    history = pane_terminal_history(context, tab_index, pane_index)
    if history:
        sys.stdout.write(history)
        sys.stdout.write(SGR_RESET)
        if not history.endswith("\n"):
            sys.stdout.write("\n")
        sys.stdout.flush()
    environment = os.environ.copy()
    startup_argv = pane_auto_run_argv(context, tab_index, pane_index)
    command = shell_launch_command(
        stored,
        context,
        tab_index,
        pane_index,
        environment,
        startup_argv,
    )
    os.execvpe(command[0], command, environment)
    raise AssertionError("os.execvpe unexpectedly returned")
